[general]
static=yes
writeprotect=no
clearglobalvars=no

[default]

[users]
exten => _1XXX,1,Dial(PJSIP/${EXTEN},30)
exten => _1XXX,n,Hangup()

; English chatbot (not yet implemented)
exten => 2000,1,Answer()
exten => 2000,n,Stasis(chatbot-en)
exten => 2000,n,Hangup()

; Kinyarwanda chatbot (not yet implemented)
exten => 3000,1,Answer()
exten => 3000,n,Stasis(chatbot-rw)
exten => 3000,n,Hangup()
