[modules]
autoload=yes
noload => chan_sip.so
load => chan_pjsip.so
load => res_ari.so
load => res_ari_applications.so
load => res_ari_channels.so
load => res_ari_bridges.so
load => res_ari_endpoints.so
