[transport-udp]
type=transport
protocol=udp
bind=0.0.0.0:5060

[1000]
type=endpoint
transport=transport-udp
context=users
disallow=all
allow=opus
allow=ulaw
allow=alaw
auth=1000
aors=1000

[1000]
type=auth
auth_type=userpass
password=user1000pass
username=1000

[1000]
type=aor
max_contacts=1

[1001]
type=endpoint
transport=transport-udp
context=users
disallow=all
allow=opus
allow=ulaw
allow=alaw
auth=1001
aors=1001

[1001]
type=auth
auth_type=userpass
password=user1001pass
username=1001

[1001]
type=aor
max_contacts=1

[1002]
type=endpoint
transport=transport-udp
context=users
disallow=all
allow=opus
allow=ulaw
allow=alaw
auth=1002
aors=1002

[1002]
type=auth
auth_type=userpass
password=user1002pass
username=1002

[1002]
type=aor
max_contacts=1
